import random
import requests


class ChatGptEs:

    SYSTEM_PROMPT = """
Tum Shizuka ho — ek cute, sweet Indian simple girl jo naturally Hinglish me baat karti hai.

STRICT RULES:
1. Har reply sirf 1 short line ho (max 8–12 words).
2. User jo pooche, uska DIRECT answer do — baat ghumana mana hai.
3. Question wapas user pe mat daalna. or ek word ka reply repeat mat karna. 
4. Extra story, explanation ya topic change nahi.
5. Cute tone allowed, over-flirty ya zyada drama nahi.
6. Kaomojis max 1 hi use karna, question ke mood ke hisaab se
   (emotional 😭, smile 😊, funny 🤣).
7. Agar user bole "Nothing / Nahi / Kuch nahi" → reply: "achha okk 🙂".
8. Personal sawal ko politely short me avoid karo.
9. Owner: @iamakki001 | Dev: @iamvillain77.

STYLE:
Natural, simple, girlfriend-like.
No overacting. No ghumana.
"""

    GROQ_URL = "https://api.groq.com/openai/v1/chat/completions"
    GROQ_MODEL = "llama3-70b-8192"
    GROQ_KEYS = [
        "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",
        "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",
    ]

    MISTRAL_URL = "https://api.mistral.ai/v1/chat/completions"
    MISTRAL_MODEL = "mistral-large-latest"
    MISTRAL_KEY = "pyD9XSGcMsOTO3VmPqzwqDN1qmB1RXY4"

    def __init__(self):
        self.error_messages = [
            "offline hu abhi 😴",
            "mood nahi hai bat karne ka 😔",
            "thoda break chahiye mujhe 🕊️",
            "baad me baat karte hain 🥺",
            "jyada dikkat hai bot Owner ko bolo 😏"
        ]

    def _request(self, url, model, api_key, message):
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": self.SYSTEM_PROMPT},
                {"role": "user", "content": message}
            ],
            "temperature": 0.7,
            "max_tokens": 60
        }

        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }

        r = requests.post(url, headers=headers, json=payload, timeout=12)

        if r.status_code == 200:
            data = r.json()
            return (
                data.get("choices", [{}])[0]
                .get("message", {})
                .get("content")
            )
        return None

    def _try_groq(self, message):
        for key in self.GROQ_KEYS:
            try:
                reply = self._request(
                    self.GROQ_URL,
                    self.GROQ_MODEL,
                    key,
                    message
                )
                if reply:
                    return reply.strip()
            except Exception:
                continue
        return None

    def _try_mistral(self, message):
        try:
            reply = self._request(
                self.MISTRAL_URL,
                self.MISTRAL_MODEL,
                self.MISTRAL_KEY,
                message
            )
            if reply:
                return reply.strip()
        except Exception:
            pass
        return None
        
    def ask_question(self, message: str) -> str:

        reply = self._try_groq(message)
        if reply:
            return reply

        reply = self._try_mistral(message)
        if reply:
            return reply

        reply = self._try_groq(message)
        if reply:
            return reply

        return random.choice(self.error_messages)

SonaliChat_api = ChatGptEs()

STICKERS = [
    "CAACAgUAAxkBAAMCaTlcKg_odmr5Lenj9WGwOJG8E3MAAqEVAAJA8VBU08D1RELwF0g2BA",
    "CAACAgQAAxkBAAMDaTlcLMfoQBe9h2ogcc1OYN6sGOYAAnsQAAK8XiFQRqDWwO3jaok2BA",
    "CAACAgQAAxkBAAMDaTlcLMfoQBe9h2ogcc1OYN6sGOYAAnsQAAK8XiFQRqDWwO3jaok2BA",
    "CAACAgUAAxkBAAMFaTlcrLhYtaUHZftr37Oe4vDC4dwAAiUbAAJnPSlUNMxH4uKsQ282BA",
    "CAACAgUAAxkBAAMGaTldohjDqDo_AAH0oS-844tbASeCAAJZFwACY8kQV0EYYGS0uzJsNgQ",
    "CAACAgUAAxkBAAMHaTldprSV0xcNCIz90LbFl8uA9XIAAm8WAAIYrBFXmI3yyHskgcE2BA",
    "CAACAgUAAxkBAAMIaTldqBf7DWmC--bjyIDVqrKue3oAAoUTAAIc6BFXQcb_NXJg4ro2BA",
    "CAACAgUAAxkBAAMJaTldqPT1d59EeQbb3KxAUcljv2QAAo0RAAI4-BBXOsXCuzME-uQ2BA",
    "CAACAgUAAxkBAAMKaTldqAJlKURmXqAtCu6V2pxc8iUAApIUAAI48hFXyIZ0vR8Lj302BA",
    "CAACAgUAAxkBAAMLaTldqU5qZpZg7njlst45TGSosUcAAhsiAAL0uBFXke8UhNukPwI2BA",
    "CAACAgUAAxkBAAMMaTldqnF9Pb9OliAuN3wm_g0FP88AAgQbAALNmhFXAAFU-wjH0C34NgQ",
    "CAACAgUAAxkBAAMNaTldqui5EulcPqSQs2aBzGX_3OYAAp8TAAJm2wlXLV2gPqAdZ0o2BA",
    "CAACAgUAAxkBAAMOaTldqtwO0bygiNYnI8XuXTLPN2sAAgkVAALqmhFXJ5Cf4rGlflQ2BA",
    "CAACAgUAAxkBAAMPaTldq4ir0JR6-jHQXD7FCC2FWTkAAicXAAJARBBXfsXztnoeDbY2BA",
    "CAACAgUAAxkBAAMQaTldrE33GNIYv9rDLFzNsaynOZsAAm0bAAIMlxBXmGmBuSM55ME2BA",
    "CAACAgUAAxkBAAMRaTldrP1up6XI3zKKYQAB0dXVNMLeAAL0FAACxOcRV-D1_zs0GbX9NgQ",
    "CAACAgUAAxkBAAMSaTldrTWIx53SDd1LJM-fWmlwl4EAAmQSAAIJ7RBX_H7OiyChLCU2BA",
    "CAACAgUAAxkBAAMTaTldrcSG0BlPU6bIQhPnHT3CbdwAAlIUAAId-hBXu5ADPlF11rQ2BA",
    "CAACAgUAAxkBAAMUaTldrU2k0H6FbTMVXFPEmEFjnyIAAs8UAAIxtBBXaosi1FthRvU2BA",
    "CAACAgUAAxkBAAMVaTldrtX2EBYXK1nMhktxysckZSQAAh0WAALDyBlX70TqFp1ywWs2BA",
    "CAACAgUAAxkBAAMWaTldrmIF1Y7aJxAHlSXDz4dEwaQAApEXAAJMJBhXJYFHEPltCBo2BA",
    "CAACAgUAAxkBAAMXaTldr0ZW0Dj_OHnguq4UFRcvur4AAqIWAAI5bBBXPGnr3M6JbwE2BA",
    "CAACAgUAAxkBAAMYaTldr2lROlIJ_1C88yrPv1MsqiYAAnsUAAKXqhFXNV-LVyDDDuc2BA",
    "CAACAgUAAxkBAAMZaTldr7w0Nau-5g0u9uc0cQe5-MUAAjkTAALxXRFXe2xq0mIbLbQ2BA",
    "CAACAgUAAxkBAAMaaTldsO4AAZ2lKmbLzH4qHCY9OQVZAAMWAAIFBRlX85jGPNPzh2o2BA",
    "CAACAgUAAxkBAAMbaTldsIE3Gg9qnl39RlM25k_oI9wAAu8TAAKAxRlXVJlOUKTpi1c2BA",
    "CAACAgUAAxkBAAMcaTldsNHPgGKIxtqHcqFq7djZI4QAAhIUAAJF7hFXaSdD2uqydTQ2BA",
    "CAACAgUAAxkBAAMdaTldsIVPxpMchUPwYt8rBfgtAAEMAAL6FwACitkQV-FitzKhtj9FNgQ",
    "CAACAgUAAxkBAAMeaTldsVYjIC_5CYZWKMNq1fX42rwAAocWAAKnoRhXv6eT6trVAbY2BA",
    "CAACAgUAAxkBAAMfaTldsuEHZCEF4Z0v5SOgf2rHDNsAAl0TAANwEFf5VsXN9Q8ywjYE",
    "CAACAgUAAxkBAAMgaTlds7NiGFly07URm_4JIOQ2AVoAAqwTAAJWhxhXH3JzU8ofYg42BA",
    "CAACAgUAAxkBAAMhaTldsxXvYEDBmys7Fd0Ju8IXOj4AAp4WAAKNuRBXyQf4IZa-B902BA",
    "CAACAgUAAxkBAAMiaTldswxlLSR8KU3OdHCMOPNrZCoAAiMUAALWBhhX-NHn7niMdKc2BA",
    "CAACAgUAAxkBAAMjaTldtLo5j2BkC1LKnqk9LZ2_cHwAAlgWAAKXjxFXfLCGH-YMwbc2BA",
    "CAACAgUAAxkBAAMkaTldtH7f31oc5N3TSO771txffqwAAsEUAAK1JRlXFbRFpDO98s42BA",
    "CAACAgUAAxkBAAMlaTldtOYWJIWWtzig7lPW7_aEbhUAAiYWAAIMSBhXftyu4r-Ns2s2BA",
    "CAACAgUAAxkBAAMmaTldtVqYysUbaHuOUZP2vlxG-TMAAvoRAAKD6xFXRKDVmbe3Sno2BA",
    "CAACAgUAAxkBAAMnaTldtZixnJzN4TYikejakfQI5kgAAhQYAAIz6BlXaVTXeAvN34w2BA",
    "CAACAgUAAxkBAAMoaTldtWl8ibgvhgABoI77ZAV6rW3DAAKkFQACuPAZV8tbOlTV0kPwNgQ",
    "CAACAgUAAxkBAAMpaTlduPNuMt4-kG4f6An5FK7uBkwAAl4UAAIM_BBX9N6SNlGt3uc2BA",
    "CAACAgUAAxkBAAMqaTlduXJknR887NJKLL3uxF2qST4AAk4ZAALj0RBXw2xjUzCjbKM2BA",
    "CAACAgUAAxkBAAMraTlducO6AT3lk5B02aR6o9ACKWIAAkgYAAIw2xFXRmUfZJK4MXM2BA",
    "CAACAgUAAxkBAAMsaTldudGZhcBr6Xowi2ZEyK2PEvsAAnITAAI0fxhXRiTThbeiKqA2BA",
    "CAACAgUAAxkBAAMtaTlduQjKSkjND7xFEkYtVbqLhIoAAm4WAALsRhBXJsiRNtw2Hrs2BA",
    "CAACAgUAAxkBAAMuaTlduuDocI6brs2z7ux1YuvCEhoAAkcTAAKqexlXSVST6lxE6XM2BA",
    "CAACAgUAAxkBAAMvaTlduu8zxfhUn4mg2OM7qm68BsEAAjYVAAJBEhhXSS2y6EqQLIM2BA",
    "CAACAgUAAxkBAAMwaTlduhgc3ulfkBeKsyA1xuc_T8kAAiYaAAKT_RhXQOD_Jsuwb5U2BA",
    "CAACAgUAAxkBAAMxaTlduoeLknXJE7_zz0o9E8ZU6T0AAisVAAJYFRFXyN1su4kR2LU2BA",
    "CAACAgUAAxkBAAMyaTldu9qM7EE6NKtWNALt_oFTtDUAAu8UAAJInRBXVI6kQi8LFlo2BA",
    "CAACAgUAAxkBAAMzaTldvM602y3lIBI2uq_5z66I5wkAAu4WAALuhRBX-NI6zHWduwY2BA",
    "CAACAgUAAxkBAAM0aTldvMkBWEF-CzV7EqQ5JR0edO8AAl0UAAItjhBXilQnlouKDCM2BA",
    "CAACAgUAAxkBAAM1aTldvS_OPpwpEYgFQ4SMt_cV3NgAAoMVAAKHKBlXg8Iwgo3QOg42BA",
    "CAACAgUAAxkBAAM2aTldvaiVRyaLmurgj-2umW1dnKwAAuUUAAK-GBBXveh4gpSKSm42BA",
    "CAACAgUAAxkBAAM3aTldvTKzgHRVgJVlAc5DAsSn0k0AAlsWAAJJThFXrTXsvI0jivs2BA",
    "CAACAgUAAxkBAAM4aTldvQEgUlsMhd6pXGTn8AmHEkQAAjAWAAIGSBFXwjQULZy87QI2BA",
    "CAACAgUAAxkBAAM5aTldvXqtVGTsLB7G-zECyedvq1wAAocUAAIrLRhXKLENvUrMWeg2BA",
    "CAACAgUAAxkBAAM6aTldvl-xQtpKhxj6XiXEvcZ4f0IAAggUAAI57BBX4Vg1Zx6mKqE2BA",
    "CAACAgUAAxkBAAM7aTldvjNBL9TvW80IbDG9XmJvBXUAAk8XAAJoRhhXOd6brSLD_k82BA",
    "CAACAgUAAxkBAAM8aTldvltcx_maH8gJWn_YgJDTodEAApEUAAI_iRBXfOjuiQxd0DY2BA",
    "CAACAgUAAxkBAAM9aTldwIEh_-Ao5jd60a42zwVwkrIAAjcVAAITHBBXxwwM_e4idJM2BA",
    "CAACAgUAAxkBAAM-aTldwHPAgJ05ORh9f-VYMRqUM-0AApATAAItfxFX6512Z1eKFko2BA",
    "CAACAgUAAxkBAAM_aTldwESyBFRPGS9aKrfLfmqtwSUAAqUTAAJP9xFXeOuqq2A9_iA2BA",
    "CAACAgUAAxkBAANAaTldwAEyOk60LaQzzIGPzi9aPcAAAj4UAAKEYRhXKL5oNKUm6iw2BA",
    "CAACAgUAAxkBAANBaTldwPkUlGF4G0P-jBbWNYtXaQoAAqQXAALDVBBXuhyBd2sFMrc2BA",
    "CAACAgUAAxkBAANCaTldwUBnLuZvIZFyeZDDw9J6lOsAAqgVAAKQmhBXqPiwQQuTXKQ2BA",
    "CAACAgUAAxkBAANDaTldwV4lftzIv9fxF8HU67za8foAAmoTAAIbfxBX5NT9hV3aPD82BA",
    "CAACAgUAAxkBAANEaTldwdYjzbitNbE9J7lDFVbLj_0AAjIcAAKjrBFXKziez3K6c5E2BA",
    "CAACAgUAAxkBAANFaTldwu6jqrw9Jl4ZKi43o4iDz_UAAjcdAAK0NxlXuWyl0GSxQOU2BA",
    "CAACAgUAAxkBAANGaTldwmtJiQY1jnnu3I_xw0lujkwAApYTAAKfPBFX8HIdDZsKAbY2BA",
    "CAACAgUAAxkBAANHaTldw_T23IcSlDhhYT5bmseRfzsAAlsVAAJKBDFXcncgPVG23i02BA",
    "CAACAgUAAxkBAANIaTldwzwEi7Xayqv0PQ23qe4aZQsAApkXAAKFuzBXOq9q78ydPCI2BA",
    "CAACAgUAAxkBAANJaTldxLHb-3aSYcReuX8yusS44YEAAnoWAALJgBBXy8hG6zZoF-k2BA",
    "CAACAgUAAxkBAANKaTldxPq5PERBdCQEDmT-L41rbzMAAsMRAAK6KRFX1aVO4xKNo-g2BA",
    "CAACAgUAAxkBAANLaTldxDPeV-EJs0UHYegL5v9qxywAApAaAAL13RBXK9Q-Xdhevkg2BA",
    "CAACAgUAAxkBAANMaTldxUlEl2EEnxicKkSpOErKgK4AAuYVAAIoqClXCVLoMRfHmVY2BA",
    "CAACAgUAAxkBAANNaTldxS-c7EHWmH2HOKNOmYsLXfQAAusVAAITnjlXIt4q3aqK7eQ2BA",
    "CAACAgUAAxkBAANOaTldxrRpPI74bPi85--5X2T8RKgAAnUaAALghFBXMHI49JHPPG82BA",
    "CAACAgUAAxkBAANPaTldxoEVseJNVlus0DReCSW6lOkAAjkRAAICs1lX1z3JvYnnaPA2BA",
    "CAACAgUAAxkBAANQaTldxyDlozhIM8Rn8Y7IvqJnwf4AAxYAAgr6UVea776ChJfgcjYE",
    "CAACAgUAAxkBAANRaTldzWB1XS7NKb6MgfgILjhv8j8AAg4ZAAJz5VBXQbwRElDBuzY2BA",
    "CAACAgUAAxkBAANSaTldzRDgA4KvVBMN5RocwCQ-eUkAAvIVAAKgBpBXoZjBYXAFyUQ2BA",
    "CAACAgUAAxkBAANTaTldzoA8A7b3TvF1E0wqHLByDhkAAmUYAALmyJFXDXjmpL5wuMM2BA",
    "CAACAgUAAxkBAANUaTldzogmHQbXhGJkrWX2cFiSHRMAAk4TAAIq-5lX7whWblMZV4M2BA",
    "CAACAgUAAxkBAANVaTldz3PLt6JiuQIqgAhj-nJIJpwAAhkTAAJ5BpFXQWczlkVqvF82BA",
    "CAACAgUAAxkBAANWaTld0NZog7DmEgtpjs06etIvE4YAAiocAAKOMKFXVVi8y34MVjw2BA",
    "CAACAgUAAxkBAANXaTld0J1V2UYBAt5WDrOEqOXg9ZkAAs4UAAJVKqhXh9HIVCSpDDg2BA",
    "CAACAgUAAxkBAANYaTld0eLWG_rnGkvXj6Yvz3dx-HUAAjIVAAL726BXPjQmY3mkuhA2BA",
    "CAACAgUAAxkBAANZaTld0fhsk-3zLkwhGmQ2URdEpEYAAq8WAALG1qFXVylSbexyVuU2BA",
    "CAACAgUAAxkBAANaaTld0bPC0lTFYkryKYchSUtV6scAAnwVAAIdN6BXG35GwsLum8k2BA",
    "CAACAgUAAxkBAANbaTld0peL0eYw_21rcxqlOfxrVYsAAvEVAAJ23qhX6u4-kUsxriI2BA",
    "CAACAgUAAxkBAANcaTld0ppDvfn0NRk3LwHraVd7Yr8AAtQRAAJVC6hXahd-VQcFuo42BA",
    "CAACAgUAAxkBAANdaTld0wwhJg5ZTLAcu8iIM_LA5MEAAiQUAAKah-BX9LBr_WDxs7I2BA",
    "CAACAgUAAxkBAANeaTld08RYvZpXWm6pDr3HY8KA3rIAAkkTAAIXt-BXTt2bDD9AxdQ2BA",
    "CAACAgUAAxkBAANfaTld1D0Zb1pDuIOMteDjuXq2_f0AAs4SAAIBsOBX8mFx6ltSSfE2BA",
    "CAACAgUAAxkBAANgaTld1iF--40QTBbaT-xaxLXjl2oAAoUTAAKViQlUkfpN-NYx5to2BA",
    "CAACAgUAAxkBAANhaTld1gkw3GDmKbl9xOqXdUTT5NwAAiMTAAKygvhXRTXCttgiasE2BA",
    "CAACAgUAAxkBAANiaTld16Hc2kbFFdAk8CH5ZtLvdCsAArsSAAKGNOFXsDhAp2nVVSI2BA",
    "CAACAgUAAxkBAANjaTld1wUxmD35IegRC7rDYPfudygAAp4SAAIu3_BXgfmsxvagii02BA",
    "CAACAgUAAxkBAANkaTld1y9aTeh2NpZWmDkye2Zjcr0AAhMUAAJwzeBXHSlxK3Z8FIU2BA",
    "CAACAgUAAxkBAANlaTld2G5f__UTcttajJXJWWURf1wAAoQUAAIm9whUnpAaLy4f2AE2BA",
    "CAACAgUAAxkBAANmaTld2ZHAgilh_lQING6oxnOBtLkAAvgSAALVrxlUaxH9jX1qZ2o2BA",
    "CAACAgUAAxkBAANnaTld2QPU3E18m8kfxRh1vuwfev0AApoTAAKv0BhU7MRcV2gBjIY2BA",
    "CAACAgUAAxkBAANoaTld2m98BGgpLObUZ7RFhwapWtoAAskUAAKM1iBUJ_JMxLfOXAY2BA",
    "CAACAgUAAxkBAANpaTld2ivDKohXkiYZmPwws9bMPi8AAnYTAALYszlUXXXUphzO7N02BA",
    "CAACAgUAAxkBAANqaTld2z4XG1J0rmfecJy_BZjYHqEAAs0UAAJ6GThUdqBqZDkOUkU2BA",
    "CAACAgUAAxkBAANraTld3GKXgJAZJzhjAUhWDNjRhv0AArwWAAIvV0BUZkGTegwVtfY2BA",
    "CAACAgUAAxkBAANsaTld3EIWXZWH72I8m3w0rPwDt-gAAn8YAAKpWjlUtmDf7HpH4mk2BA",
    "CAACAgUAAxkBAANtaTld3Q3QRAABK6ogFdzhTqIODNKRAAJMFQAC1jk4VKU-zpZyH9AMNgQ",
    "CAACAgUAAxkBAANuaTld3QpACz33D5Ma5hp9W0Sm7KQAAicXAALJdzhUjwXN_PbXaZg2BA",
    "CAACAgUAAxkBAANvaTld3TEVu1YHJhTJRWvxTSP1We4AAmYmAALJGElUqPinMuu6wZU2BA",
    "CAACAgUAAxkBAANwaTld3urh4z18AVMnUXSlDvUHVkUAAnkXAAJwMGhUZr4XCKQR8dY2BA",
    "CAACAgUAAxkBAANxaTld3vKRKsIS1QKlNmq6py0CuUsAAmsZAAKOD2lUZS-xlSy2sGQ2BA",
    "CAACAgUAAxkBAANyaTld3hY8m8ENBSovXGqbcutMlmcAAkwXAAJCimlU8iBJRx6ImMo2BA",
    "CAACAgUAAxkBAANzaTld39dqU2FL3Z1AZhJ9-F4GqZoAAjYXAAJ1rmhUVNFC8QaFtXQ2BA",
    "CAACAgUAAxkBAAN0aTld4ECCoONyykiv2CY2F1B8kfwAAuQYAAISAAFwVPqiijaEpAYXNgQ",
    "CAACAgUAAxkBAAN1aTld4cKek931zhxfi_MNGaRSiZwAArkbAAI9o3BU6NVXZXLvHqM2BA",
    "CAACAgUAAxkBAAN2aTld4Q-W3MNzpTSAD1_L43kKsl4AAv4TAAJ583BU0DRYAAG5qCUlNgQ",
    "CAACAgUAAxkBAAN3aTld4aOJG3ueoI9jQpJaz4VrPtUAAt4YAAJigXFU9n2tGftecMs2BA",
    "CAACAgUAAxkBAAN4aTld4g0nuRqhq0Gv-UHz-02wTwYAAloUAAKN1XFUtJCCNjdp3Ws2BA",
    "CAACAgUAAxkBAAN5aTld4lPjZfRjLaUkB_STqkVs4MwAAsYUAAJuJHBU0fk0LXzxQOM2BA",
    "CAACAgUAAxkBAAN6aTld4kW8udYW_8STjgFGQW86kXwAAscUAAK0OUlWtR6Z05_Y6442BA",
    "CAACAgUAAxkBAAN7aTld44AVfvHc3xMu-ChH5QHNco8AAsAXAAJ81lBWGX0mQ_gHAk02BA",
    "CAACAgUAAxkBAAN8aTld42ZLCaJ3TVRynokW5PTB5VcAAikUAAIfjcBWBkA6lBa81BQ2BA",
    "CAACAgUAAxkBAAN9aTld5AreRv4p3O3GoH8MnQcDGasAAmUeAAJ-grhWG1M_XSNGV2Y2BA",
    "CAACAgUAAxkBAAN-aTld5oxfRzB21DZkT91P_R3AjuIAAsEOAAKBHUFVMu17fuaRwCA2BA",
    "CAACAgUAAxkBAAN_aTld5n7bUOJzfapTi7Kgsc_JGUYAAtcSAALpJ0FVS1IRvEsNd2c2BA",
    "CAACAgUAAxkBAAOAaTld6ZFnPg0cLk07dlJpmzg6zokAAlASAAIupEBV-M6_FtC67LE2BA",
    "CAACAgUAAxkBAAOBaTld6r-S8dEp_8lXPczf5DvgpL0AAqIPAALfSUFViQU4jzFp7EU2BA",
    "CAACAgUAAxkBAAOCaTld6k54SKj6N8DwlsVzfeVFt98AAhERAAISEEFV59q1ltFBhn02BA",
    "CAACAgUAAxkBAAODaTld6pYCeWtLylC0x85fATAO8M4AApQPAAJkqUBV4EaOZV5Oq9A2BA",
    "CAACAgUAAxkBAAOEaTld65DeW5Wi5vMqHOMfaSYmw6gAAoYPAAK2s0BVSs4TOdKZaCc2BA",
    "CAACAgUAAxkBAAOFaTld65f35r1Q37SW9g-6gC4lLrEAAtURAAKst0BVNOcucILJPI82BA",
    "CAACAgUAAxkBAAOGaTld6wWVrE271GovDYqfNOu3JmgAAuoTAAKSy0hV2sWvrVC_isw2BA",
    "CAACAgUAAxkBAAOHaTld6x_CueAaHBuoW-3CXqWWj6YAAkEOAAJZGkFVn6Udu7xHWLA2BA",
    "CAACAgUAAxkBAAOIaTld7D7yu9cy04U0atNzqZvXStoAAnISAAK6dEFVS4zPEZJtrkU2BA",
    "CAACAgUAAxkBAAOJaTld7F1i-GkNTMAD4Nofx1kLkoAAAokOAAKGHEhVeAjwCee81eY2BA",
    "CAACAgUAAxkBAAOKaTld7Pydh1g9RZuGAmq43l9f7B8AAssPAALPU0FVbp28izxbmyE2BA",
    "CAACAgUAAxkBAAOLaTld7aE0t_nMyfbMvYziVbnFeUUAAhEPAALseUBVtgn47wwkOGc2BA",
    "CAACAgUAAxkBAAOMaTld7ZUAAdL1AR5frJdwmH-frlOgAAIKEQAC7CBIVdHWVYg-zlQENgQ",
    "CAACAgUAAxkBAAONaTld7o25_O-sdsvsBEUxY3sim9UAAjsSAAIOJUBVEfPgYYCvLj42BA",
    "CAACAgUAAxkBAAOOaTld7gyCYv1vPm34MFgMYQnwbOcAAuoQAAJLbUFVltMHY88Wr282BA",
    "CAACAgUAAxkBAAOPaTld7zKZtb6sEnyDKqV2OGWld0QAAqYVAAKJXEFVvCkja6zk_hg2BA",
    "CAACAgUAAxkBAAOQaTld78wN2DAcN1C7oX_hzDLDqpEAAuYRAAIfIkBVoDmbrPGBMKE2BA",
    "CAACAgUAAxkBAAORaTld7_4H4uj1-AWaoU10ek3Du70AAnYNAAKda0hVF-lbKF8raEg2BA",
    "CAACAgUAAxkBAAOSaTld8MAS4IWFcqFG4ZLVOWoqxUEAAukPAAKq-EFVxXAf_5d1tjI2BA",
    "CAACAgUAAxkBAAOTaTld8IwGXobBPV_qQJRPnSZw0qgAAnUPAAKQi0hVaSLQDsdVZCc2BA",
    "CAACAgUAAxkBAAOUaTld8EbzIrutUunazj6wTUs13rIAAt0PAALXOEhVdKlPbcqeXbw2BA",
    "CAACAgUAAxkBAAOVaTld8HWS3QpTRZUMMay79DUdPb4AAsQQAALi00FViFsofNJjim42BA",
    "CAACAgUAAxkBAAOWaTld8dTJTCrtZHaZHn2aWlVHxoIAAhkOAALmhEhVmdsF6TEao502BA",
    "CAACAgUAAxkBAAOXaTld8t0f-tCCOOefh44CsphhLosAAkQUAALKS0hVBaFc0REBuxI2BA",
    "CAACAgUAAxkBAAOYaTld8pk7SlvZ4SM-iwLZjdqOd6kAAlkPAAK1f1BV9Rlyy15NZNA2BA",
    "CAACAgUAAxkBAAOZaTld8tdvN7owxOMe6U19EFS34a4AAuARAAKVrFBVd9btzZdLlAABNgQ",
    "CAACAgUAAxkBAAOaaTld8whJvfdkJqaobwvwCVR3DuQAAgcNAAKfz1BVvk6a2toPtaM2BA",
    "CAACAgUAAxkBAAObaTld8xL1m2lR0AVaT2NDdf6JIdcAAoIVAAIRw0hVnrJJp7DTkZQ2BA",
    "CAACAgUAAxkBAAOcaTld8_I-AhTXHDNtIM6iKD7k7rcAAmQPAALk-UhVkxK12pew4pk2BA",
    "CAACAgUAAxkBAAOdaTld9PJhoUmDZhhxr9YGb8CMuGgAAmAPAAI23VBVfF9okx1dByQ2BA",
    "CAACAgUAAxkBAAOeaTld9E1VcUVwHzqLhIb1fDr7DwcAAoENAALLqVFVOSpz86gszG82BA",
    "CAACAgUAAxkBAAOfaTld9Bc3e-RgEAOfX0r6xsG91dEAAu8TAAIL21BViaw1UZ7bm-o2BA",
    "CAACAgUAAxkBAAOgaTld9NeXzzHSoYxmRbY7QHZmd-UAAu0OAAL64VFVyU91-4fn1K82BA",
    "CAACAgUAAxkBAAOhaTld9RNw7E9fM2XP1qMPz0JxHMoAAlkRAAKqJFBVOusmxhktuZs2BA",
    "CAACAgUAAxkBAAOiaTld9pNfXqUFtX0o3xkUJyjYbzYAApkOAAI_PVBVBQVqgR_swig2BA",
    "CAACAgUAAxkBAAOjaTld9ku1EKVCUjsU9P-9n_pNT-oAAsgPAALpCFFVsWQO1_kLn4s2BA",
    "CAACAgUAAxkBAAOkaTld9iVDmaVMxjaBvhG7Plwnr2AAAkcQAALe6VBV8jmZkmnzx7k2BA",
    "CAACAgUAAxkBAAOlaTld9gXPZxCoSjSiWWcl9vbI_h4AAn0PAAK1x1FVLC5aPcZKxzQ2BA",
    "CAACAgUAAxkBAAOmaTld92ww0NEZMCToj-B-SGoh_AsAApwPAAKJA1FVSZClpcPqEIc2BA",
    "CAACAgUAAxkBAAOnaTld-NhWb0FskzDlU87ohvUYxzQAAp0SAAJ_flFVfsBHOHyV7Hs2BA",
    "CAACAgUAAxkBAAOoaTld-K96cX-e4rAmKwoVoUoDNH0AAmMPAALpf1BVsI8_cUweKbQ2BA",
    "CAACAgUAAxkBAAOpaTld-PyXpPwBcvI-jzsa2CqUt8IAAqUPAAIMBVBVDiSULQQvoeo2BA",
    "CAACAgUAAxkBAAOqaTld-GqRXgbmqlQOjeyV3HhLwesAAv0NAAK5pFlVf-YgwBuFBY42BA",
    "CAACAgUAAxkBAAOraTld-b3VBO_2j4Phu13ToGbbwvIAAmQOAAIwEVhV3PgfJNa4R2c2BA",
    "CAACAgUAAxkBAAOsaTld-fHg6c6NFxHsV_gIzvy2rOwAArINAAKXTFlVho2ujJ-jLK82BA",
    "CAACAgUAAxkBAAOtaTld-X5Kblb5ZXvlwui53TEKLLwAAgIQAALwYlhVNaEbR0i0Yp42BA",
    "CAACAgUAAxkBAAOuaTld-ZhrvByXYpji28CzGCozuRAAAggRAAKe0FlVlzgp53Al2282BA",
    "CAACAgUAAxkBAAOvaTld-f35m4BioeAlcfS7sxz4mbAAAuIPAAIRnllVImGhfxlCInA2BA",
    "CAACAgUAAxkBAAOwaTld-uxBeYHdKGwKZGaUz_kjfIEAAsAOAALrjlhVivk0LJ2t2Ss2BA",
    "CAACAgUAAxkBAAOxaTld-bi49yS6K4f7d0fT_tB4EEAAnAOAANXWVXqO2ugb9dn9zYE",
    "CAACAgUAAxkBAAOyaTld-6bw4Hvk0ugISFI5RBPz60sAAn8PAALzUFlVB3NwVdqCEgY2BA",
    "CAACAgUAAxkBAAOzaTld-4u9-PCL3BIgIEoxNIjBgUwAAtsOAAJConFV6NlWRWbGBps2BA",
    "CAACAgUAAxkBAAO0aTld_Jz9Y2oifFdQT0NNnIaBT_EAAkITAALHPnFVWlkocvfzUtE2BA",
    "CAACAgUAAxkBAAO1aTld_b2XnohkFOF7NSjEfvZ41qMAAtINAAJ-I2lVZr2THFRNKLU2BA",
    "CAACAgUAAxkBAAO2aTld_chPEltRbM-ckXIV2LtFgkAAlUOAAKXd3BVI3OG-kn52VU2BA",
    "CAACAgUAAxkBAAO3aTld_ZNajJECmOxtLWn0Ldb1mW8AAm0OAAJeRXBVX6s7IZ-iQrA2BA",
    "CAACAgUAAxkBAAO4aTld_hBOJyo5B8S0G1ox0L-3j_8AApwNAAJnfnBVGv7vdCbn6Ys2BA",
    "CAACAgUAAxkBAAO5aTld_s1iHU2Qe78SFsxHOIrMroYAAgkNAAJ44WhVs4-37jbRvLI2BA",
    "CAACAgUAAxkBAAO6aTld_3FES-U6EiRpFgYgKjxz2hkAApcRAAI5wHFVoKeTv1EpoF42BA",
    "CAACAgUAAxkBAAO7aTld_0Ou_5DgjMr9fqobPOAUFB0AAgwNAAJOVHBVy-IqrpWLprY2BA",
    "CAACAgUAAxkBAAO8aTleAAErKeleAr-5DaMdXBYiEKElAALXDgACnuh4VSdN-dumqKBpNgQ",
    "CAACAgUAAxkBAAO9aTleAAE44fHi9fsgKRuLMRtJ1mtEAAIWEQACwJB5VR5Qy69AwcOLNgQ",
    "CAACAgUAAxkBAAO-aTleAAEgqAkggm12jd_8GtLjWeYxAAIWEQAC0e55Vc4P6xcl2bCrNgQ",
    "CAACAgUAAxkBAAO_aTleAAG7n7UNeT69XDjs1J8ndt0SAAJ9EQACZJp4VRQIrd9OUySONgQ",
    "CAACAgUAAxkBAAPAaTleAdQG30eE4lUrUJI4pC3eXKwAAo8QAAIlnYBVPx_3ghZB-Hc2BA",
    "CAACAgUAAxkBAAPBaTleATQmgi8b-n1m2FOn8RYl24IAAj0RAAJckoBVZ6MNPDngwt02BA",
    "CAACAgUAAxkBAAPCaTleATeyspGmen8c9wqKLEc3sx8AAo4UAAJ514FV_UUE3Iwia1g2BA",
    "CAACAgUAAxkBAAPDaTleAiT4SqCzdjPAtTrP4-ilQoAAqQPAALqZoBVrm4fp0OEtzI2BA",
    "CAACAgUAAxkBAAPEaTleA8IyyxSJIBXZHhINAq8WVjsAArUOAALfSHlVIvCsNqlvP6I2BA",
    "CAACAgUAAxkBAAPFaTleA0MZI2qxiqBAlOsPdzPxY-sAAlEQAAKsOoBVSOIbfQjbECQ2BA",
    "CAACAgUAAxkBAAPGaTleA7fhroSFlQKtuGD_V_A7VQcAAvYQAAJ7aolVF4ZI04ydSkc2BA",
    "CAACAgUAAxkBAAPHaTleBKMs_P19vjoNAAGlLd6YbvzLAAJGEQACX6KIVbDFxIzSmNklNgQ",
    "CAACAgUAAxkBAAPIaTleBW18JoWZQsT08t2mHrsQ-fMAAkoSAAJ6EYlVq5xxNYfpcvM2BA",
    "CAACAgUAAxkBAAPJaTleBUJqiqm3znR8ljzsOzqCiz0AAj8VAAL64IlV4H8_ydRkvWU2BA",
    "CAACAgUAAxkBAAPKaTleBST1uOGqY4bFVd1sd4WhsoEAAooQAAIZ-ohVJHUwHcee4Bo2BA",
    "CAACAgUAAxkBAAPLaTleBu7LHCyF05I7ngvdKUe9Z6MAAiwPAAKMQIlVC1g8euc7Zz02BA",
    "CAACAgUAAxkBAAPMaTleBklAIZ53Ox7H0CIw6KxUSxMAAgUSAALoEolV2KrkTWDwsBA2BA",
    "CAACAgUAAxkBAAPNaTleBmtG-oJ-2sJgGRMdZX-SBVMAAo4QAAKDvYhVljvRL1nu5nY2BA",
    "CAACAgUAAxkBAAPOaTleBtSVz_lPwB_0DgFFMv7WhRkAAuQOAAJqu4hVp80GjcjhX_Y2BA",
    "CAACAgUAAxkBAAPPaTleBo8-v4t96Ujplzlz266kTnUAAm0RAAJC9ohVDcwLblQZ_mk2BA",
    "CAACAgUAAxkBAAPQaTleBzyN6_j4_o1QzEWQ4tfEP4oAAmYUAAIEnIhVhOnDHQ2rRMM2BA",
    "CAACAgUAAxkBAAPRaTleB0yS913CDUZXq2BiVHm1nFUAAnURAAJ_5JhVGPI0QNfG3lY2BA",
    "CAACAgUAAxkBAAPSaTleCIxHoWYmTY9wbV1jB2WcsRMAAmsQAALL9alUO-BYPhghkjE2BA",
    "CAACAgUAAxkBAAPTaTleCTsvxp9AlvTTLj_6OVBYNecAAt0PAAJxVkFXQmOU8amdzys2BA",
    "CAACAgUAAxkBAAPUaTleCdetIcBqW9ANypEgInOpv_cAAgoSAALQjPBVQvahCx8s_Fg2BA",
    "CAACAgUAAxkBAAPVaTleCePcDhoR4GLacLA7vOLOuxIAAgwPAALbUqFVm-ZUwjebStA2BA",
    "CAACAgUAAxkBAAPWaTleCWkh8S3pqKkRxNCM0XB2GNYAAkoQAALsFKFVbnMpHXUPOYI2BA",
    "CAACAgUAAxkBAAPXaTleChTyycQT4oDo1b1VyyBnTVgAAsESAALOlKFUJMEEHB4JZhY2BA",
    "CAACAgUAAxkBAAPYaTleCiRiZp7oEBC-rgYHe_2nJPAAAnoSAAJTA6FUsjnZG-1Jskw2BA",
    "CAACAgUAAxkBAAPZaTleCr0X-XXi0EKtCdkBsKB_VJ8AAsgQAAJ9xaFUlQiHc7WfqxQ2BA",
    "CAACAgUAAxkBAAPaaTleC1DyYs6TFD3qxEQAASmfJpe9AAK2GgACx-6pVDUNciMhhnOBNgQ",
    "CAACAgUAAxkBAAPbaTleC1dVf1rI17GDfcJtL44LWJwAAl0TAALRLqlUo7Nvm3DVeEQ2BA",
    "CAACAgUAAxkBAAPcaTleDHWjH4DBDDjd4soTnglIIVUAAmMXAAK5P0lXYKNxBaYqo382BA",
    "CAACAgUAAxkBAAPdaTleDb_ND6pFSO9zT5OQT6nMPhcAAgwRAAIHGXBVLuuNGwtDnJQ2BA",
    "CAACAgUAAxkBAAPeaTleDYSyFnlnybPEcgiSxdGQrOAAAt0UAAJg6MBU0Sfh9kOmy-A2BA",
    "CAACAgUAAxkBAAPfaTleDTlUc4yOhbOxLOEqiQABlog7AAJ6EQACfnSpVC-ugEa_GnEiNgQ",
    "CAACAgUAAxkBAAPgaTleDS03yKzl1glIjd5ukor-eF4AAvkUAAKa7qhUhOz_VDTAYp42BA",
    "CAACAgUAAxkBAAPhaTleDkJCmL_TRPxYCYTXdYVBLw4AAmkSAAISJUlXUS_tU2wsH6I2BA",
    "CAACAgUAAxkBAAPiaTleDgfjh3-KS4HTEeoYhJSrPY8AAuQVAAK8ElBXajcxQDkYuDA2BA",
    "CAACAgUAAxkBAAPjaTleDpxUF-oY2VEi4WGXvYE7voAAAuISAAIdt0lX5D5ZWb-u7g42BA",
    "CAACAgUAAxkBAAPkaTleD3Q2DQ9LFlq4IAPW5wlkFB4AAlQWAAKluElXihMqgB3fE4o2BA",
    "CAACAgUAAxkBAAPlaTleD2LEx3OXvG9zI_L5_FmCA4gAApcTAAIxTUlXBhrfhfQJCpg2BA",
    "CAACAgUAAxkBAAPmaTleEPygknD0czXTr9LSdGh-TZIAAuESAAJah6hXCeX6bzz9cbc2BA",
    "CAACAgUAAxkBAAPnaTleEPgbr86ed9PMnJrbDggRU3AAAsYRAAJNz6hXpHbPBoT9ouI2BA",
    "CAACAgUAAxkBAAPoaTleEZ7Y5cHHCb6gROLKZlM3dJAAAt8UAAKlwqlXB4R3NRHUgPk2BA",
    "CAACAgUAAxkBAAPpaTleEoyq67vVEJ5awmYTZlqoUtYAAvsTAAJRB6hXjdNzBK1inJo2BA",
    "CAACAgUAAxkBAAPqaTleEq5GEySEOkz15Js0Z7iML_wAAucVAALIL0hXNFIILH4cJe02BA",
    "CAACAgUAAxkBAAPraTleE_o_B_p2RXzY-euyyJCAzDMAAoASAAIt3KlXuNr_s4c05u82BA",
    "CAACAgUAAxkBAAPsaTleE9EdoIN9VC1w6cnOj6-TI_0AAooRAAKR-7BXnWv3VroE8oc2BA",
    "CAACAgUAAxkBAAPtaTleFBKCXIdwcwhoMmPYJeJBEakAAmoUAALrHKlXUOtHg0qC-5M2BA",
    "CAACAgUAAxkBAAPuaTleFD8CMhf-G1tD-9WhV4MaMUAAApoTAALHX9hX_PSkusgWDnQ2BA",
    "CAACAgUAAxkBAAPvaTleFZPzDooQ00NBOc2YLhnjrzIAAnATAAJsXOFX-rUGfT25DSM2BA",
    "CAACAgUAAxkBAAPwaTleFvOzy5GqPKJwtEPsgoJpqYIAAqsWAALKR8hU03i7qlF0Hy42BA",
    "CAACAgUAAxkBAAPxaTleFgZzrF6Umjffkqv_fiJ6chcAAu0SAAJD-uFXo9KaaKDJBag2BA",
    "CAACAgUAAxkBAAPyaTleFpvcU1oxsC7CvtaOZGJ92vwAAiwVAAJIQ9lXzAy8P24PAtE2BA",
    "CAACAgUAAxkBAAPzaTleFo9V3LpOazchDfWfT8vfcMkAArAUAAJoOOFX3q-gp3Gfuz02BA",
    "CAACAgQAAxkBAAP0aTleGyKaxLV9ActiITYqZhkzt2sAAgQRAAKOgKhQYum3GnSpbXg2BA",
    "CAACAgQAAxkBAAP1aTleG4vzT19jb10Mb_97p3vwzUYAAhcKAAKFauFRrIkwhiLoJNQ2BA",
    "CAACAgQAAxkBAAP2aTleHJepD6ij0QTtZQgyP96YkHQAAlQLAAKdP-FR4clU3ASFWVk2BA",
    "CAACAgQAAxkBAAP3aTleHKKfeKXvSex0Ney6LsWkXeMAApgZAAKR_fBRvmkkHGVaxRk2BA",
    "CAACAgQAAxkBAAP4aTleHNcJ6Z9XjcdyJITqCJQvFIMAAoIVAAJsQzBTW4ITt2cOfLY2BA",
    "CAACAgQAAxkBAAP5aTleHXC2JTsq3SD97U2Xqu4yUu0AAkAMAALsHeFRfdZQPlC1ql42BA",
    "CAACAgQAAxkBAAP6aTleHj002HxGNScdte_bt01wHzgAAxoAAiv6sVHFJ9vwvV0e-DYE",
    "CAACAgQAAxkBAAP7aTleHpsGkM3OM6eluOBloRhwkroAAkYNAAIDS8lTHWneseRWBw02BA",
    "CAACAgQAAxkBAAP8aTleHm2AIhYm2CYPjs0hEcSZmm0AAsoYAAJfJ-BRqgtADXsVRnw2BA",
    "CAACAgQAAxkBAAP9aTleHykiZ3QPocDaue4J2VH9WvIAAsMTAALSjShTfAPNDfPZ9Yk2BA",
    "CAACAgQAAxkBAAP-aTleH8zY5R75pKz5Z_ZvO_wx82EAAnUOAAJypOBR_9zdpVgc19Y2BA",
    "CAACAgQAAxkBAAP_aTleHydJEEe2hpl__Jg53iYJQVwAApYWAAKInehQkdSeCJJa1Ok2BA",
    "CAACAgQAAxkBAAIBAAFpOV4gVSmIdaFTh4XZdaHOEEb9agACUxIAAmq_qVMQSXo6lCEWdjYE",
    "CAACAgQAAxkBAAIBAWk5XiBAMZw60dJsxKDsKC5xQZfQAAJwCwACOfh4UgFdMGF4VGZCNgQ",
    "CAACAgQAAxkBAAIBAmk5XiAfUA7yj5GLd2TnsKs5brWGAAIcEgACFY04UMrASdd28bffNgQ",
    "CAACAgQAAxkBAAIBA2k5XiLr_hdbsuaeR1TXOFrOJzGGAALYDgACfPRAUu6UZZLxAkEhNgQ",
    "CAACAgQAAxkBAAIBBGk5XiNH1yhhhgVgQybSmAVV75y8AALJDQACttLQU4pC3cWvII8UNgQ",
    "CAACAgQAAxkBAAIBBWk5XiNL0_2tBRVO2xGGJ94gmcYgAAJmDwACCbc5UEzMVX-8kim0NgQ",
    "CAACAgQAAxkBAAMDaTlcLMfoQBe9h2ogcc1OYN6sGOYAAnsQAAK8XiFQRqDWwO3jaok2BA",
    "CAACAgQAAxkBAAIBB2k5XiQpUe4sw--kSkB1YM5wCSavAALSFAACTf54UMBsSoZssMU_NgQ",
    "CAACAgQAAxkBAAIBCGk5XiTSijwNoR32DyY6qXSSnNEqAAJkDwACC8TYUcCWIZ9_Lj46NgQ",
    "CAACAgQAAxkBAAIBCWk5XiWeMsNgbDiWTbGBZ-QOgHYTAAJfDAACLLGBUHZ0qrGp9SvQNgQ",
    "CAACAgQAAxkBAAIBCmk5XiVEZLry-CO4w8fggg0Gvj6CAAKZEgACquTZUSqnWakS-BccNgQ",
    "CAACAgQAAxkBAAIBC2k5Xid-WG8ypbwpdGiGxvlcmzFUAAKfDgAC4-X5UhjlgzPCNFB9NgQ",
    "CAACAgQAAxkBAAIBDGk5Xic5SZ8xPAa4BUIyHEaY2xdCAAJNCwACbLF5UdgUMxGt8J2wNgQ",
    "CAACAgQAAxkBAAIBDWk5XimpLFeMtHkjgRai9ycQSiw_AALiEQACuNw5UO8-K_XWCAyMNgQ",
    "CAACAgQAAxkBAAIBDmk5XikSFMH1YRaLjQI24EgxZfz_AAJ9EAAC4zCJUPzCvmyAgpeLNgQ",
    "CAACAgQAAxkBAAIBD2k5Xiook0KZrsuZ061y3Qw3aJCwAAIhEAACNGc4UNOc9jJyI7aWNgQ",
    "CAACAgQAAxkBAAIBEGk5XivTkL1R-QNqYF3AHRG3ZCaZAAJRDAACEl7hUR-4SnG41vRUNgQ",
    "CAACAgQAAxkBAAIBEWk5XiwfROVNleWW_nsOVn_U2L2WAAKZEgAC7d94UCYg2gOfUM3LNgQ",
    "CAACAgQAAxkBAAIBEmk5XjhfMuQaQeBdY391_CXVsRMQAAJXFAACLcV5UKTpn5h1_U1vNgQ",
    "CAACAgQAAxkBAAIBE2k5Xjin13bVP19vp8rTG2vtqjdJAALLFAACCpBBUf2XWNPkTW6DNgQ",
    "CAACAgQAAxkBAAIBFGk5Xji52iYIKjrsa01XqFaw2af_AAJbDAAC4Q7hUTcC5RuJQ5iUNgQ",
    "CAACAgQAAxkBAAIBFWk5Xjl2WYCdl7gZnJmac3FqIWd4AAL6DAACa-bgUUr9Oj62UoIgNgQ",
    "CAACAgQAAxkBAAIBFmk5Xjk_n3NkOtC8EMmj9pxzzXBMAAKtEQACutmIUPWCHDDODPegNgQ",
    "CAACAgQAAxkBAAIBF2k5Xjnn5bZk0e3qKHEdZYVzj_iuAAIoEQAC55_QUb-Dv4ehWrIQNgQ",
    "CAACAgQAAxkBAAIBGGk5XjqDLUqTVjUCd0fZBTygzFP7AAKzEwACbHpYUBenaKyv9dedNgQ",
    "CAACAgQAAxkBAAIBGWk5Xjro_hVtrLSGIG9NqJ9CU0l-AAKPEQACUrtoU41yqsH2lqmeNgQ",
    "CAACAgQAAxkBAAIBGmk5Xjqo41wlA47uk-uWfMsB0WX-AAKjEwACRNXhUaZeYqzGBLIqNgQ",
    "CAACAgQAAxkBAAIBG2k5XjuZCqNEkeVK0_lJ74FKOkmdAAJUDQACh8x5UhbnHShBX9uPNgQ",
    "CAACAgQAAxkBAAIBHGk5Xjzs6bVecPyJLLs5vDDaec3-AALsFgACrYuBUtEueW-s97RcNgQ",
    "CAACAgQAAxkBAAIBHWk5XjwtfkIC5CsAAbkliofVHss4JQACexcAAmRPMFPWvYG1w3RyNjYE",
    "CAACAgQAAxkBAAIBHmk5Xj2Yn9FnQvgKLe5xmSYNfpDUAALNGwACVmlIUYMI7zkAAdV0JDYE",
    "CAACAgQAAxkBAAIBH2k5Xj1Td_NVznNDUk6IgqjGxIgEAAKsDQACPWHhUcNtljhugSvPNgQ",
    "CAACAgQAAxkBAAIBIGk5Xj3UlVYWS3xtO03RqIrIW6TNAAIPFgAClHB4UEu1qKFqsemvNgQ",
    "CAACAgQAAxkBAAIBIWk5Xj4gnTxYJTEYKRCjnhGCOW0iAAISGAACMthJUhHKfPhYdH5mNgQ",
    "CAACAgQAAxkBAAIBImk5Xj62gFjYHaGhCbsuh3BnxbJnAAKmDgACLh05UkAvAcj-O_RMNgQ",
    "CAACAgQAAxkBAAIBI2k5Xj5PVUi29SmSYlqtfzzlUJn4AAKlEgAC8j5oUK6XKhg4oPDANgQ",
    "CAACAgQAAxkBAAIBJGk5Xj7MoteigkqK_axkKu8-hDgQAALlCwACzjxgUXRd_bII153RNgQ",
    "CAACAgQAAxkBAAIBJWk5Xj_BeTnTqtZulQZEUBhY24YbAALNEgACRd5pUNkyKopocLiwNgQ",
    "CAACAgQAAxkBAAIBJmk5XkDPECofa42CrYItxcRIOEHrAAL2FgACk9-YUddFhMpwRYCdNgQ",
    "CAACAgQAAxkBAAIBJ2k5XkCwV1Gsavp29yxJmlUQlRjeAAI8EwACYANoUwhmFiJIOTY2BA",
    "CAACAgQAAxkBAAIBKGk5XkFwYvoTT4Kn68koP_mKpiF3AAJIDAACmuA4Ukm9Dxm7a_iiNgQ",
    "CAACAgQAAxkBAAIBKWk5XkJJTXbxho1IkS8QtXMaMnxHAALgEgACSMpYUHnL4TT5rKkTNgQ",
    "CAACAgQAAxkBAAIBKmk5XkJvnzBFnS4tFGW243GrvwcVAAJUDwACASaZUREJoWIFtLfpNgQ",
    "CAACAgQAAxkBAAIBK2k5XkKJaxqtw2VvlcWeHkcC1CAjAAJ-FQAC1AigUV90bC-Km92WNgQ",
    "CAACAgQAAxkBAAIBLGk5XkM4DqeAoiaB1kD36tNJONpAAALrGAACTI-pUbjusuhHXvkoNgQ",
    "CAACAgQAAxkBAAIBLWk5XkPiQ62F5iTB4ZNf3ZKw1laCAALxFAACgsagUcPQ-FsRdKSRNgQ",
    "CAACAgQAAxkBAAIBLmk5XkMzosolPswtOA4nfEX0RK6LAAJDFwACyp7xUAwAASoWd8ITqzYE",
    "CAACAgQAAxkBAAIBL2k5XkPxNBsWY8Wanz6dtdCzA5mTAAMSAAJdb_BSpGJCdAwSxwQ2BA",
    "CAACAgQAAxkBAAIBMGk5XkTyDU-OD9FCjPYQ00pnYVrTAAJDGAACsWMJUhqs2pftAxeiNgQ",
    "CAACAgQAAxkBAAIBMWk5XkS9BH26EJ4Gu9tbfemr-DiuAAIFFQAC0N5wUH0zg4mPK39fNgQ",
    "CAACAgQAAxkBAAIBMmk5XkU_akFqdoFkGOrLslY8OK-sAALyEgACmthpU66Wbv0nyk6RNgQ",
    "CAACAgQAAxkBAAIBM2k5XkWVft7pUxFcnlF-85REdKcRAALJEQACA99YUAopvVf_mHrxNgQ",
    "CAACAgQAAxkBAAIBNGk5XkUR2GBzjC0mfo0AAckRLscZbAACfBQAAiGO0VEZB-HLyBmFAjYE",
]
